#s line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Think' do
	pod 'LGActionSheet', '~> 1.0.0'
	pod 'LGAlertView', '~> 1.0.0'
	pod 'LGSideMenuController', '~> 1.0.0'
	pod 'LGDrawer', '~> 1.0.0'
    pod 'LGViews', '~> 1.0.0'
    pod 'LGHelper', '~> 1.0.0'
	pod 'LoremIpsum', '~> 1.0'
	pod 'UIImage+AF+Additions', :git => 'https://github.com/melvitax/UIImageAFAdditions.git'
	pod 'FormatterKit', '~> 1.8.0'
	pod 'JGProgressHUD'
	pod 'TOCropViewController'
	pod 'VGParallaxHeader'
	pod 'LGFilterView', '~> 1.0.0'
	pod 'MXSegmentedPager'
	pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
end

prepare_command = <<-CMD
    SUPPORTED_LOCALES="['base', 'ru', 'en']"
    find . -type d ! -name "*$SUPPORTED_LOCALES.lproj" | grep .lproj | xargs rm -rf
CMD


