#s line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Think' do
	pod 'Alamofire', '~> 1.2'
	pod 'FXBlurView', '~> 1.6.3'
	pod 'LGActionSheet', '~> 1.0.0'
	pod 'LGAlertView', '~> 1.0.0'
	pod 'LGSideMenuController', '~> 1.0.0'
	pod 'LGDrawer', '~> 1.0.0'
        pod 'LGViews', '~> 1.0.0'
    	pod 'LGHelper', '~> 1.0.0'
	pod 'LoremIpsum', '~> 1.0'
	pod 'AsyncDisplayKit', '~> 1.2.3'
	pod 'SlackTextViewController', '~> 1.5' 
	pod 'VGParallaxHeader'
	pod 'LGFilterView', '~> 1.0.0'
	pod 'MXSegmentedPager'
	pod 'Kingfisher', '~> 1.4'
	pod 'LTMorphingLabel', '~> 0.0.7'
#	pod 'StatefulViewController', "~> 0.1"
	pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
end

